#!/usr/bin/env bash
# Process and PID file

PATH_PID="/var/run/myscript.pid"

# Handle signals
trap 'echo I hate the kill command; rm -f "$PATH_PID"; exit' SIGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'rm -f "$PATH_PID"; exit' SIGQUIT

# Write own PID to file
echo $$ > "$PATH_PID"

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done

